#!/usr/bin/env python
import os
import sys
import django

# Setup Django
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cybertraining.settings')
django.setup()

from api.models import Machine

# All 106 machines with unique tasks and answers
machine_tasks = {
    # OSCP-like machines
    'Lame': [
        {'title': '1. Port Scan', 'question': 'Perform nmap scan to find open ports', 'hint': 'nmap -sC -sV 10.10.10.3', 'points': 10, 'answer': '21'},
        {'title': '2. FTP Enum', 'question': 'Check FTP for anonymous access', 'hint': 'ftp 10.10.10.3', 'points': 15, 'answer': 'anonymous'},
        {'title': '3. Exploit', 'question': 'Exploit vsftpd backdoor', 'hint': 'searchsploit vsftpd', 'points': 20, 'answer': 'vsftpd'},
        {'title': '4. User', 'question': 'Get user.txt', 'hint': 'find /home -name user.txt', 'points': 10, 'answer': 'user'},
        {'title': '5. Privesc', 'question': 'Escalate to root', 'hint': 'sudo -l', 'points': 25, 'answer': 'sudo'},
        {'title': '6. Root', 'question': 'Get root.txt', 'hint': 'cat /root/root.txt', 'points': 10, 'answer': 'root'},
    ],
    'Blue': [
        {'title': '1. Scan', 'question': 'Find open ports with nmap', 'hint': 'nmap -sC -sV -p- 10.10.10.40', 'points': 10, 'answer': '445'},
        {'title': '2. SMB Enum', 'question': 'Enumerate SMB shares', 'hint': 'enum4linux -a 10.10.10.40', 'points': 15, 'answer': 'null'},
        {'title': '3. Exploit', 'question': 'Exploit EternalBlue', 'hint': 'use exploit/windows/smb/ms17_010_psexec', 'points': 20, 'answer': 'eternalblue'},
        {'title': '4. Shell', 'question': 'Get reverse shell', 'hint': 'powershell -e', 'points': 10, 'answer': 'shell'},
        {'title': '5. User', 'question': 'Get user flag', 'hint': 'C:\\Users\\', 'points': 10, 'answer': 'user'},
        {'title': '6. Root', 'question': 'Get admin flag', 'hint': 'C:\\Users\\Administrator', 'points': 10, 'answer': 'admin'},
    ],
    'Jerry': [
        {'title': '1. Web Enum', 'question': 'Find web service ports', 'hint': 'nmap -sC -sV 10.10.10.95', 'points': 10, 'answer': '8080'},
        {'title': '2. Tomcat', 'question': 'Find Tomcat manager', 'hint': 'Check /manager/html', 'points': 15, 'answer': 'manager'},
        {'title': '3. Upload', 'question': 'Upload war shell', 'hint': 'msfvenom -p java/jsp_shell_reverse_tcp', 'points': 20, 'answer': 'war'},
        {'title': '4. Shell', 'question': 'Get shell', 'hint': 'nc -e /bin/sh', 'points': 10, 'answer': 'shell'},
        {'title': '5. User', 'question': 'Find user flag', 'hint': 'C:\\Users\\', 'points': 10, 'answer': 'tomcat'},
        {'title': '6. Root', 'question': 'Get root/admin', 'hint': 'Check services', 'points': 10, 'answer': 'system'},
    ],
    'Nibbles': [
        {'title': '1. Recon', 'question': 'Scan target', 'hint': 'nmap 10.10.10.75', 'points': 10, 'answer': '80'},
        {'title': '2. Web', 'question': 'Find hidden content', 'hint': 'gobuster -u http://10.10.10.75', 'points': 15, 'answer': 'nibbleblog'},
        {'title': '3. Exploit', 'question': 'Exploit NibbleBlog', 'hint': 'Search CVE-2015-6969', 'points': 20, 'answer': 'nibbleblog'},
        {'title': '4. Shell', 'question': 'Get limited shell', 'hint': 'Python reverse shell', 'points': 10, 'answer': 'python'},
        {'title': '5. User', 'question': 'Escalate to nibble', 'hint': 'cd /home/nibble', 'points': 10, 'answer': 'nibble'},
        {'title': '6. Root', 'question': 'Sudo abuse', 'hint': 'sudo /bin/sh', 'points': 10, 'answer': 'sudo'},
    ],
    'Bank': [
        {'title': '1. DNS', 'question': 'Check DNS records', 'hint': 'nmap -sC -sV 10.10.10.29', 'points': 10, 'answer': '53'},
        {'title': '2. Web', 'question': 'Find website', 'hint': 'dirb http://10.10.10.29', 'points': 15, 'answer': 'bank.htb'},
        {'title': '3. Upload', 'question': 'Find upload page', 'hint': 'Check /balance-transfer', 'points': 20, 'answer': 'upload'},
        {'title': '4. Shell', 'question': 'Upload reverse shell', 'hint': 'php reverse shell', 'points': 10, 'answer': 'php'},
        {'title': '5. User', 'question': 'Get user access', 'hint': '/var/www/', 'points': 10, 'answer': 'www'},
        {'title': '6. Root', 'question': 'Chown exploit', 'hint': 'chown +x', 'points': 10, 'answer': 'chown'},
    ],
    'Poison': [
        {'title': '1. Web', 'question': 'Find web ports', 'hint': 'nmap 10.10.10.84', 'points': 10, 'answer': '80'},
        {'title': '2. LFI', 'question': 'Find LFI vulnerability', 'hint': 'Test ?page= param', 'points': 15, 'answer': 'lfi'},
        {'title': '3. Read', 'question': 'Read sensitive files', 'hint': 'php://filter/convert', 'points': 20, 'answer': 'passwd'},
        {'title': '4. Creds', 'question': 'Find credentials', 'hint': 'Check /home', 'points': 10, 'answer': 'credentials'},
        {'title': '5. SSH', 'question': 'SSH access', 'hint': 'ssh user@10.10.10.84', 'points': 10, 'answer': 'ssh'},
        {'title': '6. Root', 'question': 'VNC privesc', 'hint': 'vncviewer', 'points': 10, 'answer': 'vnc'},
    ],
    'Haircut': [
        {'title': '1. Scan', 'question': 'Find web ports', 'hint': 'nmap 10.10.10.71', 'points': 10, 'answer': '80'},
        {'title': '2. Enum', 'question': 'Find directories', 'hint': 'gobuster /', 'points': 15, 'answer': 'uploads'},
        {'title': '3. Upload', 'question': 'Upload shell', 'hint': 'curl upload', 'points': 20, 'answer': 'shell'},
        {'title': '4. Execute', 'question': 'Execute shell', 'hint': 'Visit uploaded file', 'points': 10, 'answer': 'execute'},
        {'title': '5. User', 'question': 'Get user', 'hint': '/home/', 'points': 10, 'answer': 'user'},
        {'title': '6. Root', 'question': 'Cron privesc', 'hint': 'Check /etc/crontab', 'points': 10, 'answer': 'cron'},
    ],
    'Holiday': [
        {'title': '1. Recon', 'question': 'Port scan', 'hint': 'nmap 10.10.10.97', 'points': 10, 'answer': '80'},
        {'title': '2. XSS', 'question': 'Find XSS vulnerability', 'hint': 'Test search param', 'points': 15, 'answer': 'xss'},
        {'title': '3. Cookie', 'question': 'Steal admin cookie', 'hint': 'document.cookie', 'points': 20, 'answer': 'cookie'},
        {'title': '4. Admin', 'question': 'Access admin panel', 'hint': 'Set cookie', 'points': 10, 'answer': 'admin'},
        {'title': '5. Command', 'question': 'RCE on admin', 'hint': 'Command injection', 'points': 10, 'answer': 'rce'},
        {'title': '6. Root', 'question': 'Escalate', 'hint': 'sudoedit', 'points': 10, 'answer': 'sudo'},
    ],
    # Wifi/Password cracking machines
    'Wifite': [
        {'title': '1. Monitor', 'question': 'Enable monitor mode', 'hint': 'airmon-ng start wlan0', 'points': 10, 'answer': 'monitor'},
        {'title': '2. Scan', 'question': 'Scan for networks', 'hint': 'airodump-ng wlan0mon', 'points': 15, 'answer': 'networks'},
        {'title': '3. Handshake', 'question': 'Capture handshake', 'hint': 'airodump-ng --bssid', 'points': 20, 'answer': 'handshake'},
        {'title': '4. Crack', 'question': 'Crack password', 'hint': 'aircrack-ng -w wordlist', 'points': 10, 'answer': 'crack'},
        {'title': '5. Connect', 'question': 'Connect to network', 'hint': 'iwconfig wlan0', 'points': 10, 'answer': 'connect'},
        {'title': '6. Flag', 'question': 'Get network flag', 'hint': 'Check router', 'points': 10, 'answer': 'flag'},
    ],
    'Aircrack': [
        {'title': '1. Capture', 'question': 'Capture packets', 'hint': 'airodump-ng', 'points': 10, 'answer': 'capture'},
        {'title': '2. Handshake', 'question': 'Get WPA handshake', 'hint': 'aireplay-ng', 'points': 15, 'answer': 'handshake'},
        {'title': '3. Dictionary', 'question': 'Use wordlist', 'hint': 'rockyou.txt', 'points': 20, 'answer': 'dictionary'},
        {'title': '4. Crack', 'question': 'Crack the key', 'hint': 'aircrack-ng', 'points': 10, 'answer': 'key'},
        {'title': '5. Verify', 'question': 'Verify password', 'hint': 'pyrit', 'points': 10, 'answer': 'verify'},
        {'title': '6. Access', 'question': 'Get network access', 'points': 10, 'answer': 'access'},
    ],
    'ReaverPro': [
        {'title': '1. WPS', 'question': 'Find WPS routers', 'hint': 'wash -i', 'points': 10, 'answer': 'wps'},
        {'title': '2. Brute', 'question': 'Brute force WPS', 'hint': 'reaver -i', 'points': 15, 'answer': 'reaver'},
        {'title': '3. Pin', 'question': 'Reveal WPS pin', 'hint': 'pixiewps', 'points': 20, 'answer': 'pin'},
        {'title': '4. Get', 'question': 'Get password', 'hint': 'Get PSK', 'points': 10, 'answer': 'psk'},
        {'title': '5. Connect', 'question': 'Connect', 'hint': 'WPA key', 'points': 10, 'answer': 'connect'},
        {'title': '6. Flag', 'question': 'Network flag', 'points': 10, 'answer': 'flag'},
    ],
    'BullyBox': [
        {'title': '1. Setup', 'question': 'Setup bully', 'hint': 'bully -b wlan0mon', 'points': 10, 'answer': 'bully'},
        {'title': '2. Attack', 'question': 'WPS attack', 'hint': 'pixiewps', 'points': 15, 'answer': 'attack'},
        {'title': '3. Crack', 'question': 'Crack pin', 'hint': 'Brute force', 'points': 20, 'answer': 'pin'},
        {'title': '4. Get', 'question': 'Get key', 'hint': 'WPA key', 'points': 10, 'answer': 'key'},
        {'title': '5. Test', 'question': 'Test access', 'hint': 'Connect', 'points': 10, 'answer': 'test'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'EvilTwin': [
        {'title': '1. Clone', 'question': 'Clone access point', 'hint': 'airbase-ng', 'points': 10, 'answer': 'clone'},
        {'title': '2. Fake', 'question': 'Create fake AP', 'hint': 'ESSID', 'points': 15, 'answer': 'ap'},
        {'title': '3. Sniff', 'question': 'Sniff credentials', 'hint': 'ettercap', 'points': 20, 'answer': 'sniff'},
        {'title': '4. Capture', 'question': 'Capture handshake', 'hint': 'handshake', 'points': 10, 'answer': 'capture'},
        {'title': '5. Get', 'question': 'Get password', 'hint': 'Plaintext', 'points': 10, 'answer': 'password'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'Airgeddon': [
        {'title': '1. Select', 'question': 'Select interface', 'hint': 'Wireless card', 'points': 10, 'answer': 'interface'},
        {'title': '2. Mode', 'question': 'Enable monitor', 'hint': 'airmon-ng', 'points': 15, 'answer': 'monitor'},
        {'title': '3. Handshake', 'question': 'Capture handshake', 'hint': 'Handshake', 'points': 20, 'answer': 'handshake'},
        {'title': '4. Crack', 'question': 'Crack password', 'hint': 'Hashcat', 'points': 10, 'answer': 'crack'},
        {'title': '5. Access', 'question': 'Get access', 'hint': 'Connect', 'points': 10, 'answer': 'access'},
        {'title': '6. Flag', 'question': 'Network flag', 'points': 10, 'answer': 'flag'},
    ],
    'Fluxion': [
        {'title': '1. Scan', 'question': 'Scan networks', 'hint': 'Select target', 'points': 10, 'answer': 'scan'},
        {'title': '2. Clone', 'question': 'Clone login page', 'hint': 'Web template', 'points': 15, 'answer': 'clone'},
        {'title': '3. Deauth', 'question': 'Deauth attack', 'hint': 'aireplay-ng', 'points': 20, 'answer': 'deauth'},
        {'title': '4. Sniff', 'question': 'Sniff creds', 'hint': 'Fake AP', 'points': 10, 'answer': 'sniff'},
        {'title': '5. Get', 'question': 'Get password', 'hint': 'WPA key', 'points': 10, 'answer': 'password'},
        {'title': '6. Flag', 'question': 'Flag', 'points': 10, 'answer': 'flag'},
    ],
    # Password cracking tools
    'HydraSSH': [
        {'title': '1. Target', 'question': 'Set target', 'hint': 'ssh://target', 'points': 10, 'answer': 'ssh'},
        {'title': '2. User', 'question': 'Set username', 'hint': 'Username', 'points': 15, 'answer': 'user'},
        {'title': '3. Wordlist', 'question': 'Use wordlist', 'hint': 'rockyou.txt', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Attack', 'question': 'Run hydra', 'hint': 'hydra -L -P', 'points': 10, 'answer': 'hydra'},
        {'title': '5. Get', 'question': 'Get password', 'hint': 'Password found', 'points': 10, 'answer': 'password'},
        {'title': '6. Login', 'question': 'SSH login', 'hint': 'ssh user@target', 'points': 10, 'answer': 'login'},
    ],
    'HydraFTP': [
        {'title': '1. Target', 'question': 'Set FTP target', 'hint': 'ftp://target', 'points': 10, 'answer': 'ftp'},
        {'title': '2. Users', 'question': 'User list', 'hint': 'users.txt', 'points': 15, 'answer': 'users'},
        {'title': '3. Pass', 'question': 'Password list', 'hint': 'passwords.txt', 'points': 20, 'answer': 'passwords'},
        {'title': '4. Run', 'question': 'Execute hydra', 'hint': 'hydra -L -P', 'points': 10, 'answer': 'run'},
        {'title': '5. Creds', 'question': 'Get credentials', 'hint': 'Valid pair', 'points': 10, 'answer': 'creds'},
        {'title': '6. Access', 'question': 'FTP access', 'hint': 'ftp target', 'points': 10, 'answer': 'access'},
    ],
    'HydraHTTP': [
        {'title': '1. Form', 'question': 'Identify login form', 'hint': 'POST /login', 'points': 10, 'answer': 'form'},
        {'title': '2. Data', 'question': 'Find login params', 'hint': 'username=^USER^', 'points': 15, 'answer': 'params'},
        {'title': '3. Wordlist', 'question': 'Use wordlists', 'hint': 'Use hydra', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Attack', 'question': 'Brute force', 'hint': 'hydra http-post-form', 'points': 10, 'answer': 'attack'},
        {'title': '5. Success', 'question': 'Success!', 'hint': 'Get creds', 'points': 10, 'answer': 'success'},
        {'title': '6. Access', 'question': 'Access app', 'points': 10, 'answer': 'access'},
    ],
    'HydraSMB': [
        {'title': '1. Target', 'question': 'SMB target', 'hint': 'smb://target', 'points': 10, 'answer': 'smb'},
        {'title': '2. Users', 'question': 'Username list', 'hint': 'admin, root', 'points': 15, 'answer': 'users'},
        {'title': '3. Pass', 'question': 'Password list', 'hint': 'Use hydra', 'points': 20, 'answer': 'passwords'},
        {'title': '4. Brute', 'question': 'Brute force', 'hint': 'hydra -L -P', 'points': 10, 'answer': 'brute'},
        {'title': '5. Get', 'question': 'Get credentials', 'hint': 'Valid creds', 'points': 10, 'answer': 'creds'},
        {'title': '6. Shell', 'question': 'Get shell', 'hint': 'psexec', 'points': 10, 'answer': 'shell'},
    ],
    'JohnLinux': [
        {'title': '1. Hash', 'question': 'Get Linux hash', 'hint': '/etc/shadow', 'points': 10, 'answer': 'shadow'},
        {'title': '2. Unshadow', 'question': 'Combine files', 'hint': 'unshadow', 'points': 15, 'answer': 'unshadow'},
        {'title': '3. Format', 'question': 'Identify hash', 'hint': 'john --format', 'points': 20, 'answer': 'format'},
        {'title': '4. Wordlist', 'question': 'Use wordlist', 'hint': 'rockyou.txt', 'points': 10, 'answer': 'wordlist'},
        {'title': '5. Crack', 'question': 'Crack password', 'hint': 'john hash.txt', 'points': 10, 'answer': 'crack'},
        {'title': '6. Password', 'question': 'Get password', 'points': 10, 'answer': 'password'},
    ],
    'JohnWindows': [
        {'title': '1. SAM', 'question': 'Get Windows hash', 'hint': 'pwdump, mimikatz', 'points': 10, 'answer': 'sam'},
        {'title': '2. Extract', 'question': 'Extract hashes', 'hint': 'samdump2', 'points': 15, 'answer': 'hash'},
        {'title': '3. Format', 'question': 'NTLM format', 'hint': 'NT', 'points': 20, 'answer': 'ntlm'},
        {'title': '4. Wordlist', 'question': 'Password list', 'hint': 'Use john', 'points': 10, 'answer': 'list'},
        {'title': '5. Crack', 'question': 'Crack it', 'hint': 'john --format=nt', 'points': 10, 'answer': 'crack'},
        {'title': '6. Pwd', 'question': 'Password cracked', 'points': 10, 'answer': 'pwd'},
    ],
    'JohnRAR': [
        {'title': '1. File', 'question': 'Get RAR file', 'hint': 'encrypted.rar', 'points': 10, 'answer': 'rar'},
        {'title': '2. Hash', 'question': 'Extract hash', 'hint': 'rar2john', 'points': 15, 'answer': 'hash'},
        {'title': '3. Wordlist', 'question': 'Use wordlist', 'hint': 'rockyou.txt', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Crack', 'question': 'Crack RAR', 'hint': 'john hash', 'points': 10, 'answer': 'crack'},
        {'title': '5. Extract', 'question': 'Extract file', 'hint': 'unrar x', 'points': 10, 'answer': 'extract'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'HashcatMD5': [
        {'title': '1. Hash', 'question': 'Get MD5 hash', 'hint': 'Hash to crack', 'points': 10, 'answer': 'md5'},
        {'title': '2. Mode', 'question': 'Set mode 0', 'hint': '-m 0', 'points': 15, 'answer': '0'},
        {'title': '3. Wordlist', 'question': 'Use wordlist', 'hint': 'rockyou.txt', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. GPU', 'question': 'Use GPU', 'hint': '-D 1', 'points': 10, 'answer': 'gpu'},
        {'title': '5. Attack', 'question': 'Crack hash', 'hint': 'hashcat -m 0', 'points': 10, 'answer': 'crack'},
        {'title': '6. Plain', 'question': 'Get plaintext', 'points': 10, 'answer': 'plain'},
    ],
    'HashcatSHA': [
        {'title': '1. Hash', 'question': 'SHA hash', 'hint': 'SHA256', 'points': 10, 'answer': 'sha256'},
        {'title': '2. Mode', 'question': 'Mode 1400', 'hint': '-m 1400', 'points': 15, 'answer': '1400'},
        {'title': '3. Wordlist', 'question': 'Wordlist', 'hint': 'rockyou', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Crack', 'question': 'Crack it', 'hint': 'hashcat -m 1400', 'points': 10, 'answer': 'crack'},
        {'title': '5. Extract', 'question': 'Get password', 'points': 10, 'answer': 'pwd'},
        {'title': '6. Verify', 'question': 'Verify', 'hint': 'Check', 'points': 10, 'answer': 'ok'},
    ],
    'HashcatWPA': [
        {'title': '1. Handshake', 'question': 'Capture handshake', 'hint': 'airodump', 'points': 10, 'answer': 'handshake'},
        {'title': '2. Convert', 'question': 'Convert to hccapx', 'hint': 'hashcat-utils', 'points': 15, 'answer': 'hccapx'},
        {'title': '3. Mode', 'question': 'WPA mode 2500', 'hint': '-m 2500', 'points': 20, 'answer': '2500'},
        {'title': '4. Wordlist', 'question': 'Wordlist', 'hint': 'Use dict', 'points': 10, 'answer': 'dict'},
        {'title': '5. Crack', 'question': 'Crack WPA', 'hint': 'hashcat', 'points': 10, 'answer': 'crack'},
        {'title': '6. Key', 'question': 'Get WPA key', 'points': 10, 'answer': 'key'},
    ],
    'HashcatNTLM': [
        {'title': '1. Hash', 'question': 'NTLM hash', 'hint': 'From SAM', 'points': 10, 'answer': 'ntlm'},
        {'title': '2. Mode', 'question': 'Mode 1000', 'hint': '-m 1000', 'points': 15, 'answer': '1000'},
        {'title': '3. Wordlist', 'question': 'Password list', 'hint': 'rockyou', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Attack', 'question': 'Crack', 'hint': 'hashcat -m 1000', 'points': 10, 'answer': 'crack'},
        {'title': '5. Pwd', 'question': 'Password', 'points': 10, 'answer': 'pwd'},
        {'title': '6. Verify', 'question': 'Verify', 'points': 10, 'answer': 'ok'},
    ],
    'CainAbel': [
        {'title': '1. Sniff', 'question': 'Start sniffer', 'hint': 'Enable sniffer', 'points': 10, 'answer': 'sniff'},
        {'title': '2. ARP', 'question': 'ARP poison', 'hint': 'ARP spoof', 'points': 15, 'answer': 'arp'},
        {'title': '3. Sniff', 'question': 'Sniff passwords', 'hint': 'Passwords', 'points': 20, 'answer': 'passwords'},
        {'title': '4. Hash', 'question': 'Collect hashes', 'hint': 'LSA', 'points': 10, 'answer': 'hash'},
        {'title': '5. Crack', 'question': 'Crack hashes', 'hint': 'Cain cracker', 'points': 10, 'answer': 'crack'},
        {'title': '6. Creds', 'question': 'Get credentials', 'points': 10, 'answer': 'creds'},
    ],
    'Medusa': [
        {'title': '1. Target', 'question': 'Set target', 'hint': 'Target IP', 'points': 10, 'answer': 'target'},
        {'title': '2. Module', 'question': 'Select module', 'hint': 'ssh, ftp, http', 'points': 15, 'answer': 'module'},
        {'title': '3. Users', 'question': 'User list', 'hint': 'users.txt', 'points': 20, 'answer': 'users'},
        {'title': '4. Passwords', 'question': 'Password list', 'hint': 'passwords.txt', 'points': 10, 'answer': 'passwords'},
        {'title': '5. Attack', 'question': 'Run attack', 'hint': 'medusa -M', 'points': 10, 'answer': 'attack'},
        {'title': '6. Success', 'question': 'Get access', 'points': 10, 'answer': 'access'},
    ],
    # SQL Injection
    'SQLmapBasic': [
        {'title': '1. Target', 'question': 'Set target URL', 'hint': '-u http://target', 'points': 10, 'answer': 'url'},
        {'title': '2. Test', 'question': 'Test for SQLi', 'hint': 'sqlmap -u', 'points': 15, 'answer': 'test'},
        {'title': '3. Databases', 'question': 'Enumerate databases', 'hint': '--dbs', 'points': 20, 'answer': 'databases'},
        {'title': '4. Tables', 'question': 'Get tables', 'hint': '-D db --tables', 'points': 10, 'answer': 'tables'},
        {'title': '5. Columns', 'question': 'Get columns', 'hint': '--columns', 'points': 10, 'answer': 'columns'},
        {'title': '6. Dump', 'question': 'Dump data', 'hint': '--dump', 'points': 10, 'answer': 'dump'},
    ],
    'SQLmapDork': [
        {'title': '1. Google', 'question': 'Find dork', 'hint': 'inurl:php?id=', 'points': 10, 'answer': 'dork'},
        {'title': '2. Target', 'question': 'Set dork', 'hint': '-g "inurl:php?id="', 'points': 15, 'answer': 'target'},
        {'title': '3. Scan', 'question': 'Scan results', 'hint': '--batch', 'points': 20, 'answer': 'scan'},
        {'title': '4. Inject', 'question': 'SQL injection', 'hint': 'Inject', 'points': 10, 'answer': 'inject'},
        {'title': '5. DB', 'question': 'Get database', 'hint': '--dbs', 'points': 10, 'answer': 'db'},
        {'title': '6. Data', 'question': 'Extract data', 'hint': '--dump', 'points': 10, 'answer': 'data'},
    ],
    'SQLmapWAF': [
        {'title': '1. Detect', 'question': 'Detect WAF', 'hint': '--identify-waf', 'points': 10, 'answer': 'waf'},
        {'title': '2. Bypass', 'question': 'Bypass WAF', 'hint': '--tamper', 'points': 15, 'answer': 'bypass'},
        {'title': '3. Inject', 'question': 'SQL injection', 'hint': ' tamper=space2comment', 'points': 20, 'answer': 'inject'},
        {'title': '4. Enumerate', 'question': 'Enumerate DB', 'hint': '--dbs', 'points': 10, 'answer': 'enum'},
        {'title': '5. Extract', 'question': 'Extract data', 'hint': '--dump', 'points': 10, 'answer': 'extract'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'Havij': [
        {'title': '1. Target', 'question': 'Enter URL', 'hint': 'Target URL', 'points': 10, 'answer': 'url'},
        {'title': '2. Analyze', 'question': 'Analyze', 'hint': 'Analyze button', 'points': 15, 'answer': 'analyze'},
        {'title': '3. Databases', 'question': 'Get DBs', 'hint': 'Get databases', 'points': 20, 'answer': 'databases'},
        {'title': '4. Tables', 'question': 'Get tables', 'hint': 'Get tables', 'points': 10, 'answer': 'tables'},
        {'title': '5. Columns', 'question': 'Get columns', 'points': 10, 'answer': 'columns'},
        {'title': '6. Data', 'question': 'Dump data', 'points': 10, 'answer': 'data'},
    ],
    'UnionInject': [
        {'title': '1. Identify', 'question': 'Find SQLi', 'hint': 'Test UNION', 'points': 10, 'answer': 'union'},
        {'title': '2. Columns', 'question': 'Find columns', 'hint': 'ORDER BY', 'points': 15, 'answer': 'columns'},
        {'title': '3. Extract', 'question': 'Extract version', 'hint': 'version()', 'points': 20, 'answer': 'version'},
        {'title': '4. Database', 'question': 'Get DB name', 'hint': 'database()', 'points': 10, 'answer': 'database'},
        {'title': '5. Tables', 'question': 'Get tables', 'hint': 'information_schema', 'points': 10, 'answer': 'tables'},
        {'title': '6. Dump', 'question': 'Dump data', 'hint': 'SELECT data', 'points': 10, 'answer': 'dump'},
    ],
    'BlindSQLi': [
        {'title': '1. Detect', 'question': 'Detect blind SQLi', 'hint': 'Boolean-based', 'points': 10, 'answer': 'blind'},
        {'title': '2. Test', 'question': 'Test true/false', 'hint': 'AND 1=1', 'points': 15, 'answer': 'test'},
        {'title': '3. Enumerate', 'question': 'Enumerate chars', 'hint': 'SUBSTRING', 'points': 20, 'answer': 'chars'},
        {'title': '4. Length', 'question': 'Get length', 'hint': 'LENGTH', 'points': 10, 'answer': 'length'},
        {'title': '5. Extract', 'question': 'Extract data', 'hint': 'ASCII, SUBSTR', 'points': 10, 'answer': 'extract'},
        {'title': '6. Dump', 'question': 'Dump password', 'hint': 'Password hash', 'points': 10, 'answer': 'password'},
    ],
    'TimeBased': [
        {'title': '1. Detect', 'question': 'Find time-based', 'hint': 'SLEEP()', 'points': 10, 'answer': 'sleep'},
        {'title': '2. Test', 'question': 'Test injection', 'hint': 'AND SLEEP(5)', 'points': 15, 'answer': 'test'},
        {'title': '3. Enumerate', 'question': 'Enumerate', 'hint': 'BENCHMARK', 'points': 20, 'answer': 'enum'},
        {'title': '4. Extract', 'question': 'Extract data', 'hint': 'IF()', 'points': 10, 'answer': 'extract'},
        {'title': '5. Password', 'question': 'Get password', 'hint': 'Substring', 'points': 10, 'answer': 'pwd'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'ErrorBased': [
        {'title': '1. Trigger', 'question': 'Trigger error', 'hint': 'ExtractValue', 'points': 10, 'answer': 'error'},
        {'title': '2. Inject', 'question': 'Inject payload', 'hint': 'updatexml', 'points': 15, 'answer': 'inject'},
        {'title': '3. Version', 'question': 'Get version', 'hint': '@@version', 'points': 20, 'answer': 'version'},
        {'title': '4. DB', 'question': 'Get database', 'hint': 'database()', 'points': 10, 'answer': 'db'},
        {'title': '5. Tables', 'question': 'Get tables', 'hint': 'table_name', 'points': 10, 'answer': 'tables'},
        {'title': '6. Data', 'question': 'Dump data', 'points': 10, 'answer': 'data'},
    ],
    # Web Security
    'BurpSuite': [
        {'title': '1. Proxy', 'question': 'Configure proxy', 'hint': '127.0.0.1:8080', 'points': 10, 'answer': 'proxy'},
        {'title': '2. Intercept', 'question': 'Intercept request', 'hint': 'Proxy > Intercept', 'points': 15, 'answer': 'intercept'},
        {'title': '3. Analyze', 'question': 'Analyze request', 'hint': 'Analyze headers', 'points': 20, 'answer': 'analyze'},
        {'title': '4. Repeater', 'question': 'Send to Repeater', 'hint': 'Modify request', 'points': 10, 'answer': 'repeat'},
        {'title': '5. Intruder', 'question': 'Use Intruder', 'hint': 'Brute force', 'points': 10, 'answer': 'intruder'},
        {'title': '6. Exploit', 'question': 'Find vuln', 'points': 10, 'answer': 'vuln'},
    ],
    'OWASPZAP': [
        {'title': '1. Spider', 'question': 'Spider site', 'hint': 'Start spider', 'points': 10, 'answer': 'spider'},
        {'title': '2. Scan', 'question': 'Active scan', 'hint': 'Start active scan', 'points': 15, 'answer': 'scan'},
        {'title': '3. Alerts', 'question': 'View alerts', 'hint': 'Security alerts', 'points': 20, 'answer': 'alerts'},
        {'title': '4. XSS', 'question': 'Find XSS', 'hint': 'Reflected XSS', 'points': 10, 'answer': 'xss'},
        {'title': '5. SQLi', 'question': 'Find SQLi', 'hint': 'SQL Injection', 'points': 10, 'answer': 'sqli'},
        {'title': '6. Report', 'question': 'Generate report', 'points': 10, 'answer': 'report'},
    ],
    'NiktoScan': [
        {'title': '1. Target', 'question': 'Set target', 'hint': '-h target', 'points': 10, 'answer': 'target'},
        {'title': '2. Scan', 'question': 'Run scan', 'hint': 'nikto -h', 'points': 15, 'answer': 'scan'},
        {'title': '3. Plugins', 'question': 'Enable plugins', 'hint': '-Plugins', 'points': 20, 'answer': 'plugins'},
        {'title': '4. Tuning', 'question': 'Tune scan', 'hint': '-Tuning', 'points': 10, 'answer': 'tuning'},
        {'title': '5. Vulns', 'question': 'Find vulns', 'hint': 'Vulnerabilities', 'points': 10, 'answer': 'vulns'},
        {'title': '6. Report', 'question': 'Save report', 'points': 10, 'answer': 'report'},
    ],
    'DirbScan': [
        {'title': '1. Target', 'question': 'Set URL', 'hint': 'http://target', 'points': 10, 'answer': 'url'},
        {'title': '2. Wordlist', 'question': 'Set wordlist', 'hint': 'common.txt', 'points': 15, 'answer': 'wordlist'},
        {'title': '3. Scan', 'question': 'Run dirb', 'hint': 'dirb http://', 'points': 20, 'answer': 'scan'},
        {'title': '4. Hidden', 'question': 'Find dirs', 'hint': 'Directories', 'points': 10, 'answer': 'dirs'},
        {'title': '5. Files', 'question': 'Find files', 'hint': 'admin.php', 'points': 10, 'answer': 'files'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'Gobuster': [
        {'title': '1. DNS', 'question': 'DNS subdomain', 'hint': 'gobuster dns', 'points': 10, 'answer': 'dns'},
        {'title': '2. Dir', 'question': 'Directory busting', 'hint': 'gobuster dir', 'points': 15, 'answer': 'dir'},
        {'title': '3. Vhost', 'question': 'VHost scanning', 'hint': 'gobuster vhost', 'points': 20, 'answer': 'vhost'},
        {'title': '4. FUZZ', 'question': 'Fuzzing', 'hint': 'gobuster fuzz', 'points': 10, 'answer': 'fuzz'},
        {'title': '5. Found', 'question': 'Found paths', 'hint': 'discovered', 'points': 10, 'answer': 'found'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    'WPScan': [
        {'title': '1. Target', 'question': 'WordPress URL', 'hint': '--url http://', 'points': 10, 'answer': 'url'},
        {'title': '2. Enumerate', 'question': 'Enumerate users', 'hint': '--enumerate u', 'points': 15, 'answer': 'users'},
        {'title': '3. Plugins', 'question': 'Find plugins', 'hint': '--enumerate vp', 'points': 20, 'answer': 'plugins'},
        {'title': '4. Themes', 'question': 'Find themes', 'hint': '--enumerate vt', 'points': 10, 'answer': 'themes'},
        {'title': '5. Password', 'question': 'Brute force', 'hint': '--wp-passwords', 'points': 10, 'answer': 'password'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    'Sublist3r': [
        {'title': '1. Domain', 'question': 'Set domain', 'hint': '-d example.com', 'points': 10, 'answer': 'domain'},
        {'title': '2. Enum', 'question': 'Enumerate subs', 'hint': 'sublist3r -d', 'points': 15, 'answer': 'enum'},
        {'title': '3. Sources', 'question': 'Use sources', 'hint': '-e search engines', 'points': 20, 'answer': 'sources'},
        {'title': '4. Brute', 'question': 'Brute force', 'hint': '-b bruteforce', 'points': 10, 'answer': 'brute'},
        {'title': '5. Collect', 'question': 'Collect subdomains', 'hint': 'subdomains', 'points': 10, 'answer': 'subs'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'XSSBasic': [
        {'title': '1. Reflected', 'question': 'Find reflected XSS', 'hint': 'Test <script>', 'points': 10, 'answer': 'script'},
        {'title': '2. Payload', 'question': 'Test payload', 'hint': '<script>alert(1)</script>', 'points': 15, 'answer': 'alert'},
        {'title': '3. Cookie', 'question': 'Steal cookie', 'hint': '<script>document.cookie</script>', 'points': 20, 'answer': 'cookie'},
        {'title': '4. Hijack', 'question': 'Session hijack', 'hint': 'Fetch cookie', 'points': 10, 'answer': 'session'},
        {'title': '5. Inject', 'question': 'Inject code', 'hint': 'XSS payload', 'points': 10, 'answer': 'inject'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'XSSStored': [
        {'title': '1. Find', 'question': 'Find stored XSS', 'hint': 'Comment, profile', 'points': 10, 'answer': 'stored'},
        {'title': '2. Inject', 'question': 'Inject payload', 'hint': '<script>alert(1)</script>', 'points': 15, 'answer': 'inject'},
        {'title': '3. Trigger', 'question': 'Trigger XSS', 'hint': 'Visit page', 'points': 20, 'answer': 'trigger'},
        {'title': '4. Cookie', 'question': 'Steal cookies', 'hint': 'document.location', 'points': 10, 'answer': 'cookie'},
        {'title': '5. Admin', 'question': 'Attack admin', 'hint': 'Admin visits', 'points': 10, 'answer': 'admin'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'CSRFAttack': [
        {'title': '1. Find', 'question': 'Find CSRF vuln', 'hint': 'Check forms', 'points': 10, 'answer': 'csrf'},
        {'title': '2. Create', 'question': 'Create poc', 'hint': 'HTML form', 'points': 15, 'answer': 'poc'},
        {'title': '3. Deliver', 'question': 'Deliver to victim', 'hint': 'Send link', 'points': 20, 'answer': 'deliver'},
        {'title': '4. Execute', 'question': 'Attack executes', 'hint': 'Form submits', 'points': 10, 'answer': 'execute'},
        {'title': '5. Change', 'question': 'Change data', 'hint': 'Password reset', 'points': 10, 'answer': 'change'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'SSRFExploit': [
        {'title': '1. Find', 'question': 'Find SSRF', 'hint': 'url= param', 'points': 10, 'answer': 'ssrf'},
        {'title': '2. Test', 'question': 'Test localhost', 'hint': 'http://127.0.0.1', 'points': 15, 'answer': 'localhost'},
        {'title': '3. Cloud', 'question': 'AWS metadata', 'hint': '169.254.169.254', 'points': 20, 'answer': 'cloud'},
        {'title': '4. Scan', 'question': 'Internal scan', 'hint': 'Port scanning', 'points': 10, 'answer': 'scan'},
        {'title': '5. Data', 'question': 'Extract data', 'hint': 'Sensitive data', 'points': 10, 'answer': 'data'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'XXEVuln': [
        {'title': '1. Find', 'question': 'Find XXE', 'hint': 'XML upload', 'points': 10, 'answer': 'xxe'},
        {'title': '2. Inject', 'question': 'Inject XXE', 'hint': '<!ENTITY', 'points': 15, 'answer': 'entity'},
        {'title': '3. Read', 'question': 'Read file', 'hint': 'file:///', 'points': 20, 'answer': 'file'},
        {'title': '4. SSRF', 'question': 'XXE to SSRF', 'hint': 'External entity', 'points': 10, 'answer': 'ssrf'},
        {'title': '5. Data', 'question': 'Exfiltrate', 'hint': 'Data theft', 'points': 10, 'answer': 'data'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'LFIWeb': [
        {'title': '1. Find', 'question': 'Find LFI', 'hint': '?page=file', 'points': 10, 'answer': 'lfi'},
        {'title': '2. Test', 'question': 'Test with /etc/passwd', 'hint': 'page=/etc/passwd', 'points': 15, 'answer': 'passwd'},
        {'title': '3. Read', 'question': 'Read source', 'hint': 'php://filter', 'points': 20, 'answer': 'source'},
        {'title': '4. Log', 'question': 'Log poisoning', 'hint': '/var/log/apache2', 'points': 10, 'answer': 'log'},
        {'title': '5. Shell', 'question': 'Get shell', 'hint': 'Webshell', 'points': 10, 'answer': 'shell'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'RFIWeb': [
        {'title': '1. Find', 'question': 'Find RFI', 'hint': '?page=http://', 'points': 10, 'answer': 'rfi'},
        {'title': '2. Test', 'question': 'Test remote', 'hint': 'External URL', 'points': 15, 'answer': 'test'},
        {'title': '3. Shell', 'question': 'Upload shell', 'hint': 'PHP shell', 'points': 20, 'answer': 'shell'},
        {'title': '4. Execute', 'question': 'Execute code', 'hint': 'Command exec', 'points': 10, 'answer': 'exec'},
        {'title': '5. Access', 'question': 'Get access', 'hint': 'Reverse shell', 'points': 10, 'answer': 'access'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'IDORWeb': [
        {'title': '1. Find', 'question': 'Find IDOR', 'hint': '?id=1', 'points': 10, 'answer': 'idor'},
        {'title': '2. Test', 'question': 'Change ID', 'hint': '?id=2', 'points': 15, 'answer': 'change'},
        {'title': '3. Access', 'question': 'Access data', 'hint': 'User data', 'points': 20, 'answer': 'access'},
        {'title': '4. Escalate', 'question': 'Escalate', 'hint': 'Admin access', 'points': 10, 'answer': 'admin'},
        {'title': '5. Modify', 'question': 'Modify data', 'hint': 'PUT/POST', 'points': 10, 'answer': 'modify'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    # Reverse Engineering
    'Ghidra': [
        {'title': '1. Create', 'question': 'Create project', 'hint': 'New project', 'points': 10, 'answer': 'project'},
        {'title': '2. Import', 'question': 'Import binary', 'hint': 'Drag file', 'points': 15, 'answer': 'import'},
        {'title': '3. Analyze', 'question': 'Analyze binary', 'hint': 'Auto analyze', 'points': 20, 'answer': 'analyze'},
        {'title': '4. Functions', 'question': 'Find functions', 'hint': 'Function list', 'points': 10, 'answer': 'functions'},
        {'title': '5. Decompile', 'question': 'Decompile', 'hint': 'Decompiler', 'points': 10, 'answer': 'decompile'},
        {'title': '6. Flag', 'question': 'Find flag', 'points': 10, 'answer': 'flag'},
    ],
    'IDAMalware': [
        {'title': '1. Load', 'question': 'Load binary', 'hint': 'IDA Pro', 'points': 10, 'answer': 'load'},
        {'title': '2. Analyze', 'question': 'Analyze', 'hint': 'Autoanalysis', 'points': 15, 'answer': 'analyze'},
        {'title': '3. Strings', 'question': 'Find strings', 'hint': 'Strings window', 'points': 20, 'answer': 'strings'},
        {'title': '4. Functions', 'question': 'Functions', 'hint': 'Function list', 'points': 10, 'answer': 'functions'},
        {'title': '5. Xrefs', 'question': 'Cross refs', 'hint': 'Xrefs', 'points': 10, 'answer': 'xrefs'},
        {'title': '6. Key', 'question': 'Find key', 'points': 10, 'answer': 'key'},
    ],
    'Radare2': [
        {'title': '1. Open', 'question': 'Open binary', 'hint': 'r2 binary', 'points': 10, 'answer': 'open'},
        {'title': '2. Analyze', 'question': 'Analyze', 'hint': 'aaa', 'points': 15, 'answer': 'analyze'},
        {'title': '3. Seek', 'question': 'Seek main', 'hint': 's main', 'points': 20, 'answer': 'seek'},
        {'title': '4. Print', 'question': 'Disassemble', 'hint': 'pdf', 'points': 10, 'answer': 'disasm'},
        {'title': '5. Strings', 'question': 'Find strings', 'hint': 'iz', 'points': 10, 'answer': 'strings'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'OllyDbg': [
        {'title': '1. Load', 'question': 'Load exe', 'hint': 'Open file', 'points': 10, 'answer': 'load'},
        {'title': '2. Run', 'question': 'Run program', 'hint': 'F9', 'points': 15, 'answer': 'run'},
        {'title': '3. Break', 'question': 'Set breakpoint', 'hint': 'F2', 'points': 20, 'answer': 'bp'},
        {'title': '4. Step', 'question': 'Step through', 'hint': 'F8', 'points': 10, 'answer': 'step'},
        {'title': '5. Patch', 'question': 'Patch code', 'hint': 'Edit bytes', 'points': 10, 'answer': 'patch'},
        {'title': '6. Crack', 'question': 'Crackme', 'points': 10, 'answer': 'crack'},
    ],
    'Immunity': [
        {'title': '1. Load', 'question': 'Load target', 'hint': 'immunitydebugger', 'points': 10, 'answer': 'load'},
        {'title': '2. Attach', 'question': 'Attach to proc', 'hint': 'Attach', 'points': 15, 'answer': 'attach'},
        {'title': '3. Break', 'question': 'Set bp', 'hint': 'F9', 'points': 20, 'answer': 'break'},
        {'title': '4. EIP', 'question': 'Control EIP', 'hint': 'BoF', 'points': 10, 'answer': 'eip'},
        {'title': '5. Shellcode', 'question': 'Send shellcode', 'hint': 'msfvenom', 'points': 10, 'answer': 'shellcode'},
        {'title': '6. Shell', 'question': 'Get shell', 'points': 10, 'answer': 'shell'},
    ],
    'Binwalk': [
        {'title': '1. Extract', 'question': 'Extract files', 'hint': 'binwalk -e', 'points': 10, 'answer': 'extract'},
        {'title': '2. Scan', 'question': 'Scan firmware', 'hint': 'binwalk firmware.bin', 'points': 15, 'answer': 'scan'},
        {'title': '3. Find', 'question': 'Find magic', 'hint': 'Magic bytes', 'points': 20, 'answer': 'magic'},
        {'title': '4. Entropy', 'question': 'Check entropy', 'hint': '-E', 'points': 10, 'answer': 'entropy'},
        {'title': '5. Data', 'question': 'Find data', 'hint': 'Embedded data', 'points': 10, 'answer': 'data'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'Reversing101': [
        {'title': '1. Analyze', 'question': 'Analyze binary', 'hint': 'file command', 'points': 10, 'answer': 'analyze'},
        {'title': '2. Strings', 'question': 'Extract strings', 'hint': 'strings binary', 'points': 15, 'answer': 'strings'},
        {'title': '3. Disasm', 'question': 'Disassemble', 'hint': 'objdump -d', 'points': 20, 'answer': 'disasm'},
        {'title': '4. Find', 'question': 'Find password', 'hint': 'Search string', 'points': 10, 'answer': 'password'},
        {'title': '5. Patch', 'question': 'Patch binary', 'hint': 'Edit', 'points': 10, 'answer': 'patch'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    # Metasploit
    'Metasploit': [
        {'title': '1. Search', 'question': 'Search exploit', 'hint': 'search type:exploit', 'points': 10, 'answer': 'search'},
        {'title': '2. Select', 'question': 'Select exploit', 'hint': 'use exploit/...', 'points': 15, 'answer': 'use'},
        {'title': '3. Options', 'question': 'Set options', 'hint': 'set RHOST', 'points': 20, 'answer': 'options'},
        {'title': '4. Payload', 'question': 'Set payload', 'hint': 'set payload', 'points': 10, 'answer': 'payload'},
        {'title': '5. Run', 'question': 'Run exploit', 'hint': 'exploit', 'points': 10, 'answer': 'exploit'},
        {'title': '6. Shell', 'question': 'Get shell', 'points': 10, 'answer': 'shell'},
    ],
    'MsfVenom': [
        {'title': '1. Payload', 'question': 'Choose payload', 'hint': 'linux/x64/shell', 'points': 10, 'answer': 'payload'},
        {'title': '2. LHOST', 'question': 'Set LHOST', 'hint': 'Your IP', 'points': 15, 'answer': 'lhost'},
        {'title': '3. LPORT', 'question': 'Set LPORT', 'hint': 'Port', 'points': 20, 'answer': 'lport'},
        {'title': '4. Format', 'question': 'Set format', 'hint': 'elf, exe, war', 'points': 10, 'answer': 'format'},
        {'title': '5. Generate', 'question': 'Generate shellcode', 'hint': 'msfvenom -p', 'points': 10, 'answer': 'generate'},
        {'title': '6. Save', 'question': 'Save file', 'hint': '-o shell.elf', 'points': 10, 'answer': 'save'},
    ],
    'Meterpreter': [
        {'title': '1. Session', 'question': 'Get session', 'hint': 'exploit/multi/handler', 'points': 10, 'answer': 'session'},
        {'title': '2. Info', 'question': 'Get info', 'hint': 'sysinfo', 'points': 15, 'answer': 'sysinfo'},
        {'title': '3. Shell', 'question': 'Get shell', 'hint': 'shell', 'points': 20, 'answer': 'shell'},
        {'title': '4. Upload', 'question': 'Upload file', 'hint': 'upload', 'points': 10, 'answer': 'upload'},
        {'title': '5. Download', 'question': 'Download file', 'hint': 'download', 'points': 10, 'answer': 'download'},
        {'title': '6. Privesc', 'question': 'Escalate', 'hint': 'getsystem', 'points': 10, 'answer': 'privesc'},
    ],
    'Empire': [
        {'title': '1. Setup', 'question': 'Setup Empire', 'hint': './empire', 'points': 10, 'answer': 'setup'},
        {'title': '2. Listener', 'question': 'Start listener', 'hint': 'uselistener', 'points': 15, 'answer': 'listener'},
        {'title': '3. Stager', 'question': 'Create stager', 'hint': 'usestager', 'points': 20, 'answer': 'stager'},
        {'title': '4. Agent', 'question': 'Get agent', 'hint': 'Agent callback', 'points': 10, 'answer': 'agent'},
        {'title': '5. Module', 'question': 'Run module', 'hint': 'usemodule', 'points': 10, 'answer': 'module'},
        {'title': '6. Shell', 'question': 'Execute', 'points': 10, 'answer': 'shell'},
    ],
    'Covenant': [
        {'title': '1. Launch', 'question': 'Launch Covenant', 'hint': 'dotnet run', 'points': 10, 'answer': 'launch'},
        {'title': '2. Listener', 'question': 'Create listener', 'hint': 'Listeners > HTTP', 'points': 15, 'answer': 'listener'},
        {'title': '3. Grunt', 'question': 'Create grunt', 'hint': 'Launchers > Grunt', 'points': 20, 'answer': 'grunt'},
        {'title': '4. Interact', 'question': 'Interact', 'hint': 'Interact with agent', 'points': 10, 'answer': 'interact'},
        {'title': '5. Task', 'question': 'Task grunt', 'hint': 'Tasks', 'points': 10, 'answer': 'task'},
        {'title': '6. Shell', 'question': 'Shell', 'points': 10, 'answer': 'shell'},
    ],
    'BeEF': [
        {'title': '1. Hook', 'question': 'Hook browser', 'hint': '<script src=', 'points': 10, 'answer': 'hook'},
        {'title': '2. Browser', 'question': 'Command browser', 'hint': 'Commands', 'points': 15, 'answer': 'browser'},
        {'title': '3. Exec', 'question': 'Execute JS', 'hint': 'Execute JavaScript', 'points': 20, 'answer': 'exec'},
        {'title': '4. Screenshot', 'question': 'Screenshot', 'hint': 'Get screenshot', 'points': 10, 'answer': 'screenshot'},
        {'title': '5. Steal', 'question': 'Steal cookies', 'hint': 'Get cookies', 'points': 10, 'answer': 'cookies'},
        {'title': '6. Pwn', 'question': 'Pwn browser', 'points': 10, 'answer': 'pwn'},
    ],
    'ExploitDev': [
        {'title': '1. Fuzz', 'question': 'Fuzz input', 'hint': 'Pattern create', 'points': 10, 'answer': 'fuzz'},
        {'title': '2. Crash', 'question': 'Find crash', 'hint': 'Offset', 'points': 15, 'answer': 'crash'},
        {'title': '3. EIP', 'question': 'Control EIP', 'hint': 'JMP ESP', 'points': 20, 'answer': 'eip'},
        {'title': '4. Badchars', 'question': 'Find badchars', 'hint': '\x00\xff', 'points': 10, 'answer': 'badchars'},
        {'title': '5. Shellcode', 'question': 'Generate shellcode', 'hint': 'msfvenom', 'points': 10, 'answer': 'shellcode'},
        {'title': '6. Exploit', 'question': 'Get shell', 'points': 10, 'answer': 'shell'},
    ],
    # Network scanning
    'NmapScan': [
        {'title': '1. Basic', 'question': 'Basic scan', 'hint': 'nmap target', 'points': 10, 'answer': 'scan'},
        {'title': '2. Ports', 'question': 'Find ports', 'hint': '-p 1-1000', 'points': 15, 'answer': 'ports'},
        {'title': '3. Scripts', 'question': 'Default scripts', 'hint': '-sC', 'points': 20, 'answer': 'scripts'},
        {'title': '4. Version', 'question': 'Version detect', 'hint': '-sV', 'points': 10, 'answer': 'version'},
        {'title': '5. OS', 'question': 'OS detect', 'hint': '-O', 'points': 10, 'answer': 'os'},
        {'title': '6. Full', 'question': 'Full scan', 'hint': '-p- -A', 'points': 10, 'answer': 'full'},
    ],
    'NmapScripts': [
        {'title': '1. List', 'question': 'List scripts', 'hint': 'ls /usr/share/nmap/scripts', 'points': 10, 'answer': 'list'},
        {'title': '2. Category', 'question': 'Vuln scan', 'hint': '--script vuln', 'points': 15, 'answer': 'vuln'},
        {'title': '3. Brute', 'question': 'Brute force', 'hint': '--script brute', 'points': 20, 'answer': 'brute'},
        {'title': '4. Exploit', 'question': 'Exploit scripts', 'hint': '--script exploit', 'points': 10, 'answer': 'exploit'},
        {'title': '5. Discovery', 'question': 'Discovery', 'hint': '--script discovery', 'points': 10, 'answer': 'discovery'},
        {'title': '6. Auth', 'question': 'Auth scripts', 'hint': '--script auth', 'points': 10, 'answer': 'auth'},
    ],
    'NmapStealth': [
        {'title': '1. SYN', 'question': 'SYN scan', 'hint': '-sS', 'points': 10, 'answer': 'syn'},
        {'title': '2. FIN', 'question': 'FIN scan', 'hint': '-sF', 'points': 15, 'answer': 'fin'},
        {'title': '3. Xmas', 'question': 'Xmas scan', 'hint': '-sX', 'points': 20, 'answer': 'xmas'},
        {'title': '4. Null', 'question': 'Null scan', 'hint': '-sN', 'points': 10, 'answer': 'null'},
        {'title': '5. Timing', 'question': 'Timing', 'hint': '-T 4', 'points': 10, 'answer': 'timing'},
        {'title': '6. Evade', 'question': 'Evade IDS', 'hint': 'Fragmentation', 'points': 10, 'answer': 'evade'},
    ],
    'Wireshark': [
        {'title': '1. Capture', 'question': 'Capture packets', 'hint': 'Start capture', 'points': 10, 'answer': 'capture'},
        {'title': '2. Filter', 'question': 'Filter traffic', 'hint': 'tcpdump, wireshark', 'points': 15, 'answer': 'filter'},
        {'title': '3. Follow', 'question': 'Follow stream', 'hint': 'TCP stream', 'points': 20, 'answer': 'stream'},
        {'title': '4. Extract', 'question': 'Extract files', 'hint': 'File > Export', 'points': 10, 'answer': 'extract'},
        {'title': '5. Decode', 'question': 'Decode', 'hint': 'Decode as', 'points': 10, 'answer': 'decode'},
        {'title': '6. Creds', 'question': 'Find creds', 'hint': 'HTTP login', 'points': 10, 'answer': 'creds'},
    ],
    'Ettercap': [
        {'title': '1. Sniff', 'question': 'Start sniffing', 'hint': 'ettercap -i', 'points': 10, 'answer': 'sniff'},
        {'title': '2. Hosts', 'question': 'Scan hosts', 'hint': 'Scan for hosts', 'points': 15, 'answer': 'hosts'},
        {'title': '3. Poison', 'question': 'ARP poison', 'hint': 'ARP spoof', 'points': 20, 'answer': 'poison'},
        {'title': '4. Filter', 'question': 'Apply filter', 'hint': 'etterfilter', 'points': 10, 'answer': 'filter'},
        {'title': '5. Sniff', 'question': 'Sniff creds', 'hint': 'Passwords', 'points': 10, 'answer': 'passwords'},
        {'title': '6. Dump', 'question': 'Dump data', 'points': 10, 'answer': 'dump'},
    ],
    'Nessus': [
        {'title': '1. Scan', 'question': 'Create scan', 'hint': 'New scan', 'points': 10, 'answer': 'scan'},
        {'title': '2. Target', 'question': 'Set target', 'hint': 'Target IP', 'points': 15, 'answer': 'target'},
        {'title': '3. Templates', 'question': 'Select template', 'hint': 'Basic network', 'points': 20, 'answer': 'template'},
        {'title': '4. Launch', 'question': 'Launch scan', 'hint': 'Launch', 'points': 10, 'answer': 'launch'},
        {'title': '5. Results', 'question': 'View results', 'hint': 'Vulnerabilities', 'points': 10, 'answer': 'results'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    'OpenVAS': [
        {'title': '1. Task', 'question': 'Create task', 'hint': 'New task', 'points': 10, 'answer': 'task'},
        {'title': '2. Config', 'question': 'Set config', 'hint': 'Full scan', 'points': 15, 'answer': 'config'},
        {'title': '3. Target', 'question': 'Set target', 'hint': 'Target host', 'points': 20, 'answer': 'target'},
        {'title': '4. Schedule', 'question': 'Schedule', 'hint': 'Now', 'points': 10, 'answer': 'schedule'},
        {'title': '5. Start', 'question': 'Start scan', 'hint': 'Start', 'points': 10, 'answer': 'start'},
        {'title': '6. Report', 'question': 'Get report', 'hint': 'Results', 'points': 10, 'answer': 'report'},
    ],
    'Netcat': [
        {'title': '1. Connect', 'question': 'Connect to port', 'hint': 'nc -nv target 80', 'points': 10, 'answer': 'connect'},
        {'title': '2. Listen', 'question': 'Listen port', 'hint': 'nc -lvp 4444', 'points': 15, 'answer': 'listen'},
        {'title': '3. File', 'question': 'Transfer file', 'hint': 'nc target < file', 'points': 20, 'answer': 'transfer'},
        {'title': '4. Reverse', 'question': 'Reverse shell', 'hint': 'rm -f /tmp/p; mkfifo', 'points': 10, 'answer': 'shell'},
        {'title': '5. Banner', 'question': 'Grab banner', 'hint': 'nc -v target', 'points': 10, 'answer': 'banner'},
        {'title': '6. Port', 'question': 'Port scan', 'hint': 'nc -zv target', 'points': 10, 'answer': 'port'},
    ],
    'Responder': [
        {'title': '1. Start', 'question': 'Start Responder', 'hint': './Responder.py -I eth0', 'points': 10, 'answer': 'start'},
        {'title': '2. LLMNR', 'question': 'Poison LLMNR', 'hint': 'LLMNR/NBT-NS', 'points': 15, 'answer': 'llmnr'},
        {'title': '3. Capture', 'question': 'Capture hash', 'hint': 'NTVLM hash', 'points': 20, 'answer': 'hash'},
        {'title': '4. Relay', 'question': 'NTLM relay', 'hint': 'Relay attack', 'points': 10, 'answer': 'relay'},
        {'title': '5. Crack', 'question': 'Crack hash', 'hint': 'john, hashcat', 'points': 10, 'answer': 'crack'},
        {'title': '6. Access', 'question': 'Get access', 'points': 10, 'answer': 'access'},
    ],
    'Impacket': [
        {'title': '1. Secretsdump', 'question': 'Dump secrets', 'hint': 'secretsdump.py', 'points': 10, 'answer': 'secrets'},
        {'title': '2. PsExec', 'question': ' psexec.py', 'hint': 'Remote execute', 'points': 15, 'answer': 'psexec'},
        {'title': '3. WMIExec', 'question': 'wmiexec.py', 'hint': 'WMI access', 'points': 20, 'answer': 'wmiexec'},
        {'title': '4. Kerberoast', 'question': 'Kerberoast', 'hint': 'GetSPNs.py', 'points': 10, 'answer': 'kerberoast'},
        {'title': '5. Golden', 'question': 'Golden ticket', 'hint': 'ticketer.py', 'points': 10, 'answer': 'golden'},
        {'title': '6. Pass', 'question': 'Password attack', 'points': 10, 'answer': 'attack'},
    ],
    'DNSEnum': [
        {'title': '1. Zone', 'question': 'Zone transfer', 'hint': 'dig axfr', 'points': 10, 'answer': 'zone'},
        {'title': '2. Enum', 'question': 'Enumerate', 'hint': 'dnsenum', 'points': 15, 'answer': 'enum'},
        {'title': '3. Brute', 'question': 'Brute force', 'hint': 'Subdomains', 'points': 20, 'answer': 'brute'},
        {'title': '4. Reverse', 'question': 'Reverse DNS', 'hint': 'Reverse lookup', 'points': 10, 'answer': 'reverse'},
        {'title': '5. Records', 'question': 'Get records', 'hint': 'MX, TXT', 'points': 10, 'answer': 'records'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'SNMPScan': [
        {'title': '1. Scan', 'question': 'SNMP scan', 'hint': 'snmpwalk', 'points': 10, 'answer': 'scan'},
        {'title': '2. Community', 'question': 'Default community', 'hint': 'public', 'points': 15, 'answer': 'public'},
        {'title': '3. Enum', 'question': 'Enumerate', 'hint': 'snmpcheck', 'points': 20, 'answer': 'enum'},
        {'title': '4. Users', 'question': 'Get users', 'hint': '1.3.6.1.4.1.77', 'points': 10, 'answer': 'users'},
        {'title': '5. Processes', 'question': 'Processes', 'hint': 'Running proc', 'points': 10, 'answer': 'processes'},
        {'title': '6. Creds', 'question': 'Credentials', 'points': 10, 'answer': 'creds'},
    ],
    'SMBEnum': [
        {'title': '1. Null', 'question': 'Null session', 'hint': 'enum4linux -N', 'points': 10, 'answer': 'null'},
        {'title': '2. Shares', 'question': 'List shares', 'hint': 'smbclient -L', 'points': 15, 'answer': 'shares'},
        {'title': '3. Users', 'question': 'Enum users', 'hint': 'RID cycling', 'points': 20, 'answer': 'users'},
        {'title': '4. Sessions', 'question': 'Sessions', 'hint': 'Net sessions', 'points': 10, 'answer': 'sessions'},
        {'title': '5. Passwords', 'question': 'Password policy', 'hint': 'Password policy', 'points': 10, 'answer': 'policy'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    # Phishing
    'SETPhish': [
        {'title': '1. Social', 'question': 'Social Engineering', 'hint': 'seeker Spear phishing', 'points': 10, 'answer': 'social'},
        {'title': '2. Template', 'question': 'Choose template', 'hint': 'Gmail, Yahoo', 'points': 15, 'answer': 'template'},
        {'title': '3. Payload', 'question': 'Create payload', 'hint': 'Java applet', 'points': 20, 'answer': 'payload'},
        {'title': '4. Send', 'question': 'Send email', 'hint': 'Send email', 'points': 10, 'answer': 'send'},
        {'title': '5. Catch', 'question': 'Catch creds', 'hint': 'Credentials', 'points': 10, 'answer': 'catch'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'Gophish': [
        {'title': '1. Dashboard', 'question': 'Dashboard', 'hint': 'Create campaign', 'points': 10, 'answer': 'dashboard'},
        {'title': '2. Template', 'question': 'Email template', 'hint': 'HTML email', 'points': 15, 'answer': 'template'},
        {'title': '3. Landing', 'question': 'Landing page', 'hint': 'Fake login', 'points': 20, 'answer': 'landing'},
        {'title': '4. Profile', 'question': 'Sending profile', 'hint': 'SMTP', 'points': 10, 'answer': 'profile'},
        {'title': '5. Launch', 'question': 'Launch campaign', 'hint': 'Send', 'points': 10, 'answer': 'launch'},
        {'title': '6. Results', 'question': 'View results', 'points': 10, 'answer': 'results'},
    ],
    'Maltego': [
        {'title': '1. Transform', 'question': 'Run transforms', 'hint': 'Transforms', 'points': 10, 'answer': 'transform'},
        {'title': '2. Entity', 'question': 'Add entity', 'hint': 'Domain, Person', 'points': 15, 'answer': 'entity'},
        {'title': '3. Recon', 'question': 'OSINT recon', 'hint': 'Gather intel', 'points': 20, 'answer': 'recon'},
        {'title': '4. Social', 'question': 'Social media', 'hint': 'Twitter, FB', 'points': 10, 'answer': 'social'},
        {'title': '5. Network', 'question': 'Network info', 'hint': 'IP, DNS', 'points': 10, 'answer': 'network'},
        {'title': '6. Map', 'question': 'Map results', 'points': 10, 'answer': 'map'},
    ],
    'TheHarvester': [
        {'title': '1. Domain', 'question': 'Set domain', 'hint': '-d domain.com', 'points': 10, 'answer': 'domain'},
        {'title': '2. Source', 'question': 'Choose source', 'hint': 'Google, Bing', 'points': 15, 'answer': 'source'},
        {'title': '3. Gather', 'question': 'Gather data', 'hint': 'theHarvester', 'points': 20, 'answer': 'gather'},
        {'title': '4. Emails', 'question': 'Find emails', 'hint': 'Email addresses', 'points': 10, 'answer': 'emails'},
        {'title': '5. Hosts', 'question': 'Find hosts', 'hint': 'Subdomains', 'points': 10, 'answer': 'hosts'},
        {'title': '6. Creds', 'question': 'Get creds', 'points': 10, 'answer': 'creds'},
    ],
    # Privilege Escalation
    'Linpeas': [
        {'title': '1. Transfer', 'question': 'Transfer linpeas', 'hint': 'wget, curl', 'points': 10, 'answer': 'transfer'},
        {'title': '2. Execute', 'question': 'Execute linpeas', 'hint': 'chmod +x', 'points': 15, 'answer': 'execute'},
        {'title': '3. Sudo', 'question': 'Check sudo', 'hint': 'Sudo -l', 'points': 20, 'answer': 'sudo'},
        {'title': '4. SUID', 'question': 'Check SUID', 'hint': 'SUID bins', 'points': 10, 'answer': 'suid'},
        {'title': '5. Cron', 'question': 'Check cron', 'hint': 'Cron jobs', 'points': 10, 'answer': 'cron'},
        {'title': '6. Kernel', 'question': 'Kernel exploit', 'points': 10, 'answer': 'kernel'},
    ],
    'Winpeas': [
        {'title': '1. Transfer', 'question': 'Transfer winpeas', 'hint': 'PowerShell', 'points': 10, 'answer': 'transfer'},
        {'title': '2. Execute', 'question': 'Run winpeas', 'hint': 'winPEAS.bat', 'points': 15, 'answer': 'execute'},
        {'title': '3. Services', 'question': 'Check services', 'hint': 'Misconfig', 'points': 20, 'answer': 'services'},
        {'title': '4. Registry', 'question': 'Check registry', 'hint': 'Autorun', 'points': 10, 'answer': 'registry'},
        {'title': '5. Paths', 'question': 'PATH misconfig', 'hint': 'PATH', 'points': 10, 'answer': 'paths'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    'GTFOBins': [
        {'title': '1. Find', 'question': 'Find binary', 'hint': 'which find', 'points': 10, 'answer': 'find'},
        {'title': '2. Sudo', 'question': 'Check sudo', 'hint': 'sudo -l', 'points': 15, 'answer': 'sudo'},
        {'title': '3. GTFO', 'question': 'GTFO lookup', 'hint': 'gtfobins.github.io', 'points': 20, 'answer': 'gtfo'},
        {'title': '4. Exploit', 'question': 'Use exploit', 'hint': 'GTFO command', 'points': 10, 'answer': 'exploit'},
        {'title': '5. Shell', 'question': 'Get shell', 'hint': 'Shell escape', 'points': 10, 'answer': 'shell'},
        {'title': '6. Root', 'question': 'Get root', 'points': 10, 'answer': 'root'},
    ],
    'SudoMisconfig': [
        {'title': '1. Sudo', 'question': 'Check sudo', 'hint': 'sudo -l', 'points': 10, 'answer': 'sudo'},
        {'title': '2. Binary', 'question': 'Find binary', 'hint': 'awk, vim', 'points': 15, 'answer': 'binary'},
        {'title': '3. GTFO', 'question': 'Check GTFOBins', 'hint': 'gtfobins', 'points': 20, 'answer': 'gtfo'},
        {'title': '4. Execute', 'question': 'Execute', 'hint': 'sudo awk', 'points': 10, 'answer': 'execute'},
        {'title': '5. Shell', 'question': 'Shell', 'hint': '/bin/sh', 'points': 10, 'answer': 'shell'},
        {'title': '6. Root', 'question': 'Root!', 'points': 10, 'answer': 'root'},
    ],
    'CronPrivesc': [
        {'title': '1. Find', 'question': 'Find cron', 'hint': 'ls /etc/cron.d', 'points': 10, 'answer': 'cron'},
        {'title': '2. Script', 'question': 'Find script', 'hint': '.sh file', 'points': 15, 'answer': 'script'},
        {'title': '3. Write', 'question': 'Write script', 'hint': 'echo malicious', 'points': 20, 'answer': 'write'},
        {'title': '4. Wait', 'question': 'Wait for cron', 'hint': 'Sleep', 'points': 10, 'answer': 'wait'},
        {'title': '5. Execute', 'question': 'Code executes', 'hint': 'As root', 'points': 10, 'answer': 'execute'},
        {'title': '6. Root', 'question': 'Root!', 'points': 10, 'answer': 'root'},
    ],
    'KernelExploit': [
        {'title': '1. OS', 'question': 'Identify OS', 'hint': 'uname -a', 'points': 10, 'answer': 'os'},
        {'title': '2. Kernel', 'question': 'Find kernel version', 'hint': 'Kernel version', 'points': 15, 'answer': 'kernel'},
        {'title': '3. Search', 'question': 'Search exploit', 'hint': 'searchsploit', 'points': 20, 'answer': 'search'},
        {'title': '4. Download', 'question': 'Download exploit', 'hint': 'wget, git', 'points': 10, 'answer': 'download'},
        {'title': '5. Compile', 'question': 'Compile exploit', 'hint': 'gcc', 'points': 10, 'answer': 'compile'},
        {'title': '6. Run', 'question': 'Run and root', 'points': 10, 'answer': 'root'},
    ],
    'DirtyCow': [
        {'title': '1. Identify', 'question': 'Identify kernel', 'hint': 'uname -r', 'points': 10, 'answer': 'kernel'},
        {'title': '2. Search', 'question': 'Find exploit', 'hint': 'Dirty COW CVE-2016-5195', 'points': 15, 'answer': 'exploit'},
        {'title': '3. Download', 'question': 'Download', 'hint': 'wget dirtycow.c', 'points': 20, 'answer': 'download'},
        {'title': '4. Compile', 'question': 'Compile', 'hint': 'gcc -pthread', 'points': 10, 'answer': 'compile'},
        {'title': '5. Run', 'question': 'Run exploit', 'hint': './dcow', 'points': 10, 'answer': 'run'},
        {'title': '6. Root', 'question': 'Get root', 'hint': 'Password changed', 'points': 10, 'answer': 'root'},
    ],
    'SUIDExploit': [
        {'title': '1. Find', 'question': 'Find SUID', 'hint': 'find / -perm -4000', 'points': 10, 'answer': 'suid'},
        {'title': '2. List', 'question': 'List binaries', 'hint': 'SUID bins', 'points': 15, 'answer': 'list'},
        {'title': '3. GTFO', 'question': 'Check GTFOBins', 'hint': 'gtfobins', 'points': 20, 'answer': 'gtfo'},
        {'title': '4. Exploit', 'question': 'Exploit SUID', 'hint': 'Binary exploit', 'points': 10, 'answer': 'exploit'},
        {'title': '5. Shell', 'question': 'Get shell', 'hint': 'Shell escape', 'points': 10, 'answer': 'shell'},
        {'title': '6. Root', 'question': 'Root', 'points': 10, 'answer': 'root'},
    ],
    'WindowsPrivesc': [
        {'title': '1. Info', 'question': 'System info', 'hint': 'systeminfo', 'points': 10, 'answer': 'systeminfo'},
        {'title': '2. User', 'question': 'Who am i', 'hint': 'whoami /all', 'points': 15, 'answer': 'whoami'},
        {'title': '3. Admin', 'question': 'Check admin', 'hint': 'net localgroup', 'points': 20, 'answer': 'admin'},
        {'title': '4. Services', 'question': 'Services', 'hint': 'sc query', 'points': 10, 'answer': 'services'},
        {'title': '5. Registry', 'question': 'Registry', 'hint': 'HKLM\\...', 'points': 10, 'answer': 'registry'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    'ServiceExploit': [
        {'title': '1. Service', 'question': 'Find service', 'hint': 'sc query', 'points': 10, 'answer': 'service'},
        {'title': '2. Path', 'question': 'Check path', 'hint': 'sc qc', 'points': 15, 'answer': 'path'},
        {'title': '3. Write', 'question': 'Write access', 'hint': 'Write to path', 'points': 20, 'answer': 'write'},
        {'title': '4. Malicious', 'question': 'Create payload', 'hint': 'msfvenom', 'points': 10, 'answer': 'malicious'},
        {'title': '5. Restart', 'question': 'Restart service', 'hint': 'sc stop, sc start', 'points': 10, 'answer': 'restart'},
        {'title': '6. Shell', 'question': 'Get shell', 'points': 10, 'answer': 'shell'},
    ],
    # Cryptography
    'HashCrack': [
        {'title': '1. Identify', 'question': 'Identify hash', 'hint': 'Hash type', 'points': 10, 'answer': 'identify'},
        {'title': '2. Format', 'question': 'Hash format', 'hint': 'MD5, SHA', 'points': 15, 'answer': 'format'},
        {'title': '3. Wordlist', 'question': 'Use wordlist', 'hint': 'rockyou.txt', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Crack', 'question': 'Crack hash', 'hint': 'Hashcat, John', 'points': 10, 'answer': 'crack'},
        {'title': '5. Salt', 'question': 'Salting', 'hint': 'Salt value', 'points': 10, 'answer': 'salt'},
        {'title': '6. Plain', 'question': 'Get plaintext', 'points': 10, 'answer': 'plain'},
    ],
    'RSAcrack': [
        {'title': '1. Key', 'question': 'Get RSA key', 'hint': 'Public key', 'points': 10, 'answer': 'key'},
        {'title': '2. Factor', 'question': 'Factor N', 'hint': 'n = p * q', 'points': 15, 'answer': 'factor'},
        {'title': '3. Private', 'question': 'Calculate d', 'hint': 'd = e^-1 mod φ(n)', 'points': 20, 'answer': 'private'},
        {'title': '4. Decrypt', 'question': 'Decrypt', 'hint': 'c^d mod n', 'points': 10, 'answer': 'decrypt'},
        {'title': '5. Cipher', 'question': 'Cipher text', 'hint': 'Encrypted', 'points': 10, 'answer': 'cipher'},
        {'title': '6. Plain', 'question': 'Get plaintext', 'points': 10, 'answer': 'plain'},
    ],
    'AESattack': [
        {'title': '1. Mode', 'question': 'Identify mode', 'hint': 'CBC, ECB', 'points': 10, 'answer': 'mode'},
        {'title': '2. IV', 'question': 'Find IV', 'hint': 'Initialization vector', 'points': 15, 'answer': 'iv'},
        {'title': '3. Padding', 'question': 'Padding oracle', 'hint': 'CBC padding', 'points': 20, 'answer': 'padding'},
        {'title': '4. Decrypt', 'question': 'Decrypt', 'hint': 'Decryption', 'points': 10, 'answer': 'decrypt'},
        {'title': '5. Key', 'question': 'Find key', 'hint': 'AES key', 'points': 10, 'answer': 'key'},
        {'title': '6. Plain', 'question': 'Get plaintext', 'points': 10, 'answer': 'plain'},
    ],
    'SSL_TLS': [
        {'title': '1. Scan', 'question': 'SSL scan', 'hint': 'nmap --script ssl-enum', 'points': 10, 'answer': 'scan'},
        {'title': '2. Cert', 'question': 'Get cert', 'hint': 'openssl s_client', 'points': 15, 'answer': 'cert'},
        {'title': '3. Weak', 'question': 'Find weak ciphers', 'hint': 'Weak crypto', 'points': 20, 'answer': 'weak'},
        {'title': '4. Heartbleed', 'question': 'Heartbleed', 'hint': 'CVE-2014-0160', 'points': 10, 'answer': 'heartbleed'},
        {'title': '5. Poodle', 'question': 'POODLE', 'hint': 'SSLv3', 'points': 10, 'answer': 'poodle'},
        {'title': '6. Exploit', 'question': 'Exploit', 'points': 10, 'answer': 'exploit'},
    ],
    'PGPCrack': [
        {'title': '1. PGP', 'question': 'Find PGP', 'hint': '.asc file', 'points': 10, 'answer': 'pgp'},
        {'title': '2. Extract', 'question': 'Extract hash', 'hint': 'gpg2john', 'points': 15, 'answer': 'extract'},
        {'title': '3. Wordlist', 'question': 'Use wordlist', 'hint': 'Password list', 'points': 20, 'answer': 'wordlist'},
        {'title': '4. Crack', 'question': 'Crack', 'hint': 'John, Hashcat', 'points': 10, 'answer': 'crack'},
        {'title': '5. Import', 'question': 'Import key', 'hint': 'gpg --import', 'points': 10, 'answer': 'import'},
        {'title': '6. Decrypt', 'question': 'Decrypt file', 'points': 10, 'answer': 'decrypt'},
    ],
    'Base64Decode': [
        {'title': '1. Identify', 'question': 'Identify base64', 'hint': '== at end', 'points': 10, 'answer': 'base64'},
        {'title': '2. Decode', 'question': 'Decode', 'hint': 'echo | base64 -d', 'points': 15, 'answer': 'decode'},
        {'title': '3. Multiple', 'question': 'Multiple layers', 'hint': 'Decode again', 'points': 20, 'answer': 'multiple'},
        {'title': '4. Binary', 'question': 'Binary decode', 'hint': 'Base64 > binary', 'points': 10, 'answer': 'binary'},
        {'title': '5. File', 'question': 'Decode file', 'hint': 'Base64 decode', 'points': 10, 'answer': 'file'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'X509Attack': [
        {'title': '1. Cert', 'question': 'Get certificate', 'hint': '.pem, .crt', 'points': 10, 'answer': 'cert'},
        {'title': '2. Parse', 'question': 'Parse cert', 'hint': 'openssl x509', 'points': 15, 'answer': 'parse'},
        {'title': '3. Extract', 'question': 'Extract pubkey', 'hint': 'Public key', 'points': 20, 'answer': 'extract'},
        {'title': '4. Weak', 'question': 'Weak crypto', 'hint': 'RSA small', 'points': 10, 'answer': 'weak'},
        {'title': '5. Attack', 'question': 'Attack', 'hint': 'Wiener attack', 'points': 10, 'answer': 'attack'},
        {'title': '6. Private', 'question': 'Get private', 'points': 10, 'answer': 'private'},
    ],
    # Forensics
    'Volatility': [
        {'title': '1. Profile', 'question': 'Identify profile', 'hint': 'imageinfo', 'points': 10, 'answer': 'profile'},
        {'title': '2. Process', 'question': 'List processes', 'hint': 'pslist', 'points': 15, 'answer': 'process'},
        {'title': '3. Shell', 'question': 'Find shell', 'hint': 'cmdshell', 'points': 20, 'answer': 'shell'},
        {'title': '4. Network', 'question': 'Network', 'hint': 'netscan', 'points': 10, 'answer': 'network'},
        {'title': '5. Plugins', 'question': 'Run plugins', 'hint': 'malfind', 'points': 10, 'answer': 'malfind'},
        {'title': '6. Dump', 'question': 'Dump memory', 'points': 10, 'answer': 'dump'},
    ],
    'Autopsy': [
        {'title': '1. Case', 'question': 'Create case', 'hint': 'New case', 'points': 10, 'answer': 'case'},
        {'title': '2. Image', 'question': 'Add image', 'hint': 'Disk image', 'points': 15, 'answer': 'image'},
        {'title': '3. Analyze', 'question': 'Analyze', 'hint': 'Run analysis', 'points': 20, 'answer': 'analyze'},
        {'title': '4. Files', 'question': 'Find files', 'hint': 'Keyword search', 'points': 10, 'answer': 'files'},
        {'title': '5. Deleted', 'question': 'Deleted files', 'hint': 'Recover', 'points': 10, 'answer': 'deleted'},
        {'title': '6. Timeline', 'question': 'Timeline', 'points': 10, 'answer': 'timeline'},
    ],
    'Foremost': [
        {'title': '1. Image', 'question': 'Disk image', 'hint': 'dd, .img', 'points': 10, 'answer': 'image'},
        {'title': '2. Config', 'question': 'Configure', 'hint': 'foremost.conf', 'points': 15, 'answer': 'config'},
        {'title': '3. Carve', 'question': 'Carve files', 'hint': 'foremost -i', 'points': 20, 'answer': 'carve'},
        {'title': '4. Images', 'question': 'Find images', 'hint': 'jpg, png', 'points': 10, 'answer': 'images'},
        {'title': '5. Docs', 'question': 'Documents', 'hint': 'pdf, doc', 'points': 10, 'answer': 'docs'},
        {'title': '6. Extract', 'question': 'Extract', 'points': 10, 'answer': 'extract'},
    ],
    'Steghide': [
        {'title': '1. Embed', 'question': 'Find embedded', 'hint': 'steghide extract', 'points': 10, 'answer': 'embed'},
        {'title': '2. Extract', 'question': 'Extract data', 'hint': 'steghide extract -sf', 'points': 15, 'answer': 'extract'},
        {'title': '3. Password', 'question': 'Password', 'hint': 'Passphrase', 'points': 20, 'answer': 'password'},
        {'title': '4. Brute', 'question': 'Brute force', 'hint': 'stegcracker', 'points': 10, 'answer': 'brute'},
        {'title': '5. Info', 'question': 'Get info', 'hint': 'steghide info', 'points': 10, 'answer': 'info'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'StegSolve': [
        {'title': '1. Open', 'question': 'Open image', 'hint': 'Open file', 'points': 10, 'answer': 'open'},
        {'title': '2. Planes', 'question': 'Color planes', 'hint': 'RGB planes', 'points': 15, 'answer': 'planes'},
        {'title': '3. Extract', 'question': 'Extract data', 'hint': 'Data extract', 'points': 20, 'answer': 'extract'},
        {'title': '4. Bit', 'question': 'LSB', 'hint': 'Bit planes', 'points': 10, 'answer': 'lsb'},
        {'title': '5. Combine', 'question': 'Combine images', 'hint': 'Image combiner', 'points': 10, 'answer': 'combine'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'BinwalkFirmware': [
        {'title': '1. Scan', 'question': 'Scan firmware', 'hint': 'binwalk firmware.bin', 'points': 10, 'answer': 'scan'},
        {'title': '2. Extract', 'question': 'Extract', 'hint': 'binwalk -e', 'points': 15, 'answer': 'extract'},
        {'title': '3. Squash', 'question': 'SquashFS', 'hint': 'Unsquash', 'points': 20, 'answer': 'squash'},
        {'title': '4. Files', 'question': 'Find files', 'hint': 'Embedded files', 'points': 10, 'answer': 'files'},
        {'title': '5. Secrets', 'question': 'Find secrets', 'hint': 'Passwords', 'points': 10, 'answer': 'secrets'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
    'MemoryDump': [
        {'title': '1. Dump', 'question': 'Memory dump', 'hint': 'win32dd, magnet', 'points': 10, 'answer': 'dump'},
        {'title': '2. Analyze', 'question': 'Analyze', 'hint': 'Volatility', 'points': 15, 'answer': 'analyze'},
        {'title': '3. Processes', 'question': 'Processes', 'hint': 'pslist', 'points': 20, 'answer': 'processes'},
        {'title': '4. Injected', 'question': 'Injected code', 'hint': 'malfind', 'points': 10, 'answer': 'injected'},
        {'title': '5. Secrets', 'question': 'Dump secrets', 'hint': 'lsadump', 'points': 10, 'answer': 'secrets'},
        {'title': '6. Flag', 'question': 'Get flag', 'points': 10, 'answer': 'flag'},
    ],
}

# Default tasks for machines not in the list
default_tasks = [
    {'title': '1. Recon', 'question': 'Perform reconnaissance', 'hint': 'Scan target', 'points': 10, 'answer': 'scan'},
    {'title': '2. Enum', 'question': 'Enumerate', 'hint': 'Enumerate', 'points': 15, 'answer': 'enum'},
    {'title': '3. Exploit', 'question': 'Exploit', 'hint': 'Exploit', 'points': 20, 'answer': 'exploit'},
    {'title': '4. Shell', 'question': 'Get shell', 'hint': 'Shell', 'points': 10, 'answer': 'shell'},
    {'title': '5. User', 'question': 'Get user', 'hint': 'User', 'points': 10, 'answer': 'user'},
    {'title': '6. Root', 'question': 'Get root', 'hint': 'Root', 'points': 10, 'answer': 'root'},
]

# Update all machines
count = 0
for machine in Machine.objects.all():
    machine_name = machine.name
    if machine_name in machine_tasks:
        machine.tasks = machine_tasks[machine_name]
    else:
        machine.tasks = default_tasks
    machine.save()
    count += 1
    print(f"Updated: {machine_name}")

print(f"\nTotal machines updated: {count}")
print(f"Total machines in database: {Machine.objects.count()}")
