# Generated by Django 4.2.7 on 2026-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machine_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='walkthrough_url',
            field=models.URLField(blank=True, help_text='URL to download walkthrough PDF'),
        ),
    ]
