# Generated by Django 4.2.7 on 2026-03-09 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_machine_walkthrough_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CyberTraining VPN', max_length=100)),
                ('server_ip', models.GenericIPAddressField(help_text='VPN server IP address')),
                ('server_port', models.IntegerField(default=1194, help_text='OpenVPN port')),
                ('server_protocol', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP')], default='udp', max_length=10)),
                ('vpn_network', models.CharField(default='10.8.0.0/24', help_text='VPN network range', max_length=50)),
                ('dns_servers', models.JSONField(default=list, help_text='DNS servers for VPN')),
                ('is_active', models.BooleanField(default=True)),
                ('ca_cert', models.TextField(blank=True, help_text='CA Certificate')),
                ('ta_key', models.TextField(blank=True, help_text='TLS Auth Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPNUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('config_file', models.TextField(help_text='OpenVPN configuration file content')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'username')},
            },
        ),
    ]
