# Generated by Django 4.2.7 on 2026-03-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_machineinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineinstance',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this instance expires', null=True),
        ),
        migrations.AlterField(
            model_name='machineinstance',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('expired', 'Expired'), ('error', 'Error')], default='stopped', max_length=20),
        ),
    ]
