# Generated by Django 4.2.7 on 2026-03-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vpnconfig_lab_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnconfig',
            name='vpn_network',
            field=models.CharField(default='10.8.0.0/24', help_text='VPN client network range (OpenVPN clients)', max_length=50),
        ),
    ]
