# Generated by Django 4.2.7 on 2026-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vpnconfig_vpn_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='download_url',
            field=models.URLField(blank=True, help_text='URL to download challenge files (ZIP, etc.)'),
        ),
    ]
