# Generated by Django 4.2.7 on 2026-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_machine_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_machines',
            field=models.JSONField(default=list),
        ),
    ]
