# Generated by Django 4.2.7 on 2026-03-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_frame_id'),
        ('api', '0013_alter_frame_id_alter_frame_name_alter_machine_name_and_more'),
    ]

    operations = [
    ]
