# Generated by Django 4.2.7 on 2026-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20260316_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_tasks',
            field=models.JSONField(default=dict),
        ),
    ]
