# Generated by Django 4.2.7 on 2026-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='tasks',
            field=models.JSONField(default=list),
        ),
    ]
