# Generated by Django 4.2.7 on 2026-03-09 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_vpnconfig_vpnuserconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=64)),
                ('container_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('error', 'Error')], default='stopped', max_length=20)),
                ('docker_image', models.CharField(help_text='Docker image to use', max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('machine', 'user')},
            },
        ),
    ]
